# NutriHelp Security Scanner V2.0 Configuration
scanner:
  name: "NutriHelp Security Scanner V2.0"
  version: "2.0.0"
  description: "Specialized security scanner for NutriHelp project"
  
  # Scan Settings
  scan_settings:
    max_file_size_mb: 50
    timeout_seconds: 300
    parallel_scanning: false

  # Supported File Extensions
  file_extensions:
    - .js
    - .ts
    - .py
    - .sql
    - .json
    - .yaml
    - .yml
    - .env

  # Excluded Directories
  exclude_directories:
    - node_modules
    - .git
    - __pycache__
    - venv
    - .venv
    - dist
    - build
    - uploads
    - temp

# Plugin Configuration
plugins:
  # JWT Security Plugin
  jwt_missing_protection:
    enabled: true
    severity_override: null
    config:
      # Public endpoints (do not require JWT protection)
      public_endpoints:
        - "/login"
        - "/register"
        - "/signup"
        - "/health"
        - "/docs"
        - "/api-docs"
        - "/public"

      # JWT Middleware Patterns
      jwt_middleware_patterns:
        - "authenticateToken"
        - "verifyToken"
        - "jwtAuth"
        - "requireAuth"
        - "checkJWT"
  
  jwt_configuration:
    enabled: true
    severity_override: null
    config:
      min_secret_length: 32
      check_weak_secrets: true
      validate_expiry: true
      check_algorithm: true

  # RLS Security Plugin
  rls_missing_protection:
    enabled: true
    severity_override: null
    config:
      # Sensitive tables (require RLS protection)
      sensitive_tables:
        - "users"
        - "user_profiles"
        - "auth_logs"
        - "user_sessions"
        - "recipes"
        - "meal_plans"
        - "appointments"
        - "medical_predictions"
        - "user_feedback"
        - "notifications"

      # RLS Indicators
      rls_indicators:
        - "auth.uid()"
        - "current_user"
        - "user_id"
        - "auth_user"
        - "rls"
        - "row level security"

# Report Settings
reports:
  # General Settings
  include_source_snippets: true
  max_snippet_lines: 5
  include_file_paths: true
  include_timestamps: true

  # Grouping Settings
  group_by_severity: true
  sort_by_severity: true

  # Output Formats
  formats:
    json:
      enabled: true
      indent: 2
      include_metadata: true
    
    html:
      enabled: true
      template: "default"
      include_css: true
      include_js: false
    
    text:
      enabled: true
      max_width: 120
      include_summary: true

# Logging Settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_output: false
  file_path: "logs/scanner.log"