logging:
  file_output: false
  file_path: logs/scanner.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
plugins:
  jwt_configuration:
    config:
      check_env_files: true
      min_secret_length: 32
    enabled: true
  jwt_missing_protection:
    config:
      check_middleware: true
      check_routes: true
      exclude_paths:
      - /health
      - /api-docs
    enabled: true
  rls_missing_protection_disabled:
    config:
      rls_indicators:
      - auth.uid()
      - current_user
      - user_id
      - auth_user
      - rls
      - row level security
      sensitive_tables:
      - users
      - user_profiles
      - auth_logs
      - user_sessions
      - recipes
      - meal_plans
      - appointments
      - medical_predictions
      - user_feedback
      - notifications
    enabled: false
    severity_override: null
reports:
  formats:
    html:
      enabled: false
      include_css: true
      include_js: false
      template: default
    json:
      enabled: false
      include_metadata: true
      indent: 2
    text:
      enabled: false
      include_summary: true
      max_width: 120
  group_by_severity: true
  include_file_paths: true
  include_source_snippets: true
  include_timestamps: true
  max_snippet_lines: 5
  sort_by_severity: true
scanner:
  description: Specialized security scanner for NutriHelp project
  exclude_directories:
  - node_modules
  - .git
  - __pycache__
  - venv
  - .venv
  - dist
  - build
  - uploads
  - temp
  file_extensions:
  - .js
  - .ts
  - .py
  - .sql
  - .json
  - .yaml
  - .yml
  - .env
  name: NutriHelp Security Scanner V2.0
  scan_settings:
    max_file_size_mb: 50
    parallel_scanning: false
    timeout_seconds: 300
  version: 2.0.0
